version: "3.7"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    hostname: mysql.php.ec
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: entrar123
    ports:
      - "3306:3306"
    volumes:
      - /home/ivanstalyn/ectur/mysql/data:/var/lib/mysql
      - /home/ivanstalyn/ectur/mysql/config:/etc/mysql/conf.d
